name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - name: Enable IP Forwarding
        run: sudo sysctl -w net.ipv4.ip_forward=1
      - name: Run Debian 12
        run: docker run -d --name debian_ptero --privileged -p 2222:22 debian:bookworm sleep infinity
      - name: Setup SSH
        run: |
          docker exec debian_ptero apt update
          docker exec debian_ptero apt install -y openssh-server sudo curl gnupg jq iproute2
          docker exec debian_ptero mkdir -p /var/run/sshd
          docker exec debian_ptero sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
          docker exec debian_ptero sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
          docker exec debian_ptero service ssh restart
      - name: Create User
        run: |
          docker exec debian_ptero useradd -m -s /bin/bash Davi
          docker exec debian_ptero passwd -d Davi
          docker exec debian_ptero usermod -aG sudo Davi
      - name: Start Pinggy
        run: docker run -d --name pinggy_tunnel --net=host pinggy/pinggy -p 443 -R0:localhost:22 yU5bqrJJwh1+force+udp@us.free.pinggy.io
      - name: Display Info
        run: |
          echo SSH_COMMAND_READY
          echo ssh Davi@evqqh-13-87-231-100.run.pinggy-free.link -p 29272
          sleep 5
          docker logs pinggy_tunnel
      - name: Keep Alive
        run: docker logs -f debian_ptero
